name: Deploy Docusaurus to swiss-architecture-knife.github.io

on:
  push:
    branches:
      - main  # Adjust to your default branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus
        run: npm run build

      - name: Deploy to GitHub Pages Repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Clone the target GitHub Pages repository
          git clone https://github.com/swiss-architecture-knife/docs.git --depth 1 --branch main --single-branch pages-output

          # Copy built files to the GitHub Pages repo
          rsync -av --delete build/ pages-output/

          cd pages-output
          git add .
          git commit -m "Deploy new site version from docs-repo 🚀" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.DEPLOY_PAT }}@github.com/swiss-architecture-knife/swiss-architecture-knife.github.io.git main
